### PR TITLE
Set UTF-8 for all ConfigObj instances

### LINKED ISSUE #8239: Illegal character in `create_dconfig_from_params`
Hi! I was using Tribler and THIS happened! :cry:
```
Traceback (most recent call last):
  File "D:\a\tribler\tribler\src\tribler\core\restapi\rest_manager.py", line 107, in error_middleware
  File "D:\a\tribler\tribler\src\tribler\core\restapi\rest_manager.py", line 162, in required_components_middleware
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
  File "D:\a\tribler\tribler\src\tribler\core\libtorrent\restapi\downloads_endpoint.py", line 428, in add_download
  File "D:\a\tribler\tribler\src\tribler\core\libtorrent\restapi\downloads_endpoint.py", line 106, in create_dconfig_from_params
  File "D:\a\tribler\tribler\src\tribler\core\libtorrent\download_manager\download_config.py", line 132, in from_defaults
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\configobj\__init__.py", line 2108, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\u044f' in position 20: ordinal not in range(128)

```

### PR DESCRIPTION
**Pull request by qstokkink**
Fixes #8239

This PR:

 - Fixes a syntax error in the string formatting in `SaveAs.tsx`.
 - Updates all `ConfigObj` instances to use `utf-8`, instead of the default `ascii`.

Notes:
- This is a confirmed fix for the setup described in https://github.com/Tribler/tribler/issues/8239#issuecomment-2451886971
- The compile step uncovered that we use the "error" key inconsistently. Sometimes it's a string and sometimes it's a mapping.

### CODE REVIEW

**Comment by qstokkink** [comment]
validate

File: src/tribler/ui/src/dialogs/SaveAs.tsx [hunk 1]
```diff
@@ -155,8 +155,11 @@ export default function SaveAs(props: SaveAsProps & JSX.IntrinsicAttributes & Di
 
             if (response === undefined) {
                 setError(`${t("ToastErrorGetMetainfo")} ${t("ToastErrorGenNetworkErr")}`);
+            } else if ('error' in response && typeof response.error === 'object') {
+                let errorCode = response.error as {handled: boolean, code: string, message: string};
+                setError(`${t("ToastErrorGetMetainfo")} ${errorCode.code}`);
             } else if (isErrorDict(response)) {
-                setError(`t("ToastErrorGetMetainfo")} ${response.error}`);
+                setError(`${t("ToastErrorGetMetainfo")} ${response.error}`);
```
Comment (qstokkink) [inline src/tribler/ui/src/dialogs/SaveAs.tsx:162]: This is a bit icky, but for the scope of this PR I decided not to make our custom REST API errors consistent with the unhandled errors.

**Review by egbertbouman — APPROVED** [review]
